iiwa_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
  gains:
    iiwa_joint_1: {p: 100, d: 1, i: 0, i_clamp: 1}
    iiwa_joint_2: {p: 100, d: 1, i: 0, i_clamp: 1}
    iiwa_joint_3: {p: 100, d: 1, i: 0, i_clamp: 1}
    iiwa_joint_4: {p: 100, d: 1, i: 0, i_clamp: 1}
    iiwa_joint_5: {p: 100, d: 1, i: 0, i_clamp: 1}
    iiwa_joint_6: {p: 100, d: 1, i: 0, i_clamp: 1}
    iiwa_joint_7: {p: 100, d: 1, i: 0, i_clamp: 1}
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.05
    iiwa_joint_1: {trajectory: 0.01, goal: 0.001}
    iiwa_joint_2: {trajectory: 0.01, goal: 0.002}
    iiwa_joint_3: {trajectory: 0.01, goal: 0.001}
    iiwa_joint_4: {trajectory: 0.01, goal: 0.002}
    iiwa_joint_5: {trajectory: 0.01, goal: 0.001}
    iiwa_joint_6: {trajectory: 0.01, goal: 0.001}
    iiwa_joint_7: {trajectory: 0.01, goal: 0.001}

gazebo_ros_control:
  pid_gains:
    iiwa_joint_1: {p: 800, i: 0, d: 3}
    iiwa_joint_2: {p: 20000, i: 0, d: 3}
    iiwa_joint_3: {p: 8000, i: 0, d: 3}
    iiwa_joint_4: {p: 20000, i: 0, d: 3}
    iiwa_joint_5: {p: 8000, i: 0, d: 3}
    iiwa_joint_6: {p: 1000, i: 0, d: 3}
    iiwa_joint_7: {p: 1000, i: 0, d: 3}

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50 